[package]
name = "burpsuite_kit_demo_http_history"
version = "0.1.0"
authors = ["vkill <vkill.net@gmail.com>"]
edition = "2018"

[dependencies]
burpsuite-kit = { path = "../..", version = "=0.1.2" }
base64 = "0.13"
http1-spec = "0.1"
serde_json = "1.0"

pretty_env_logger = "0.4"
log = "0.4"
